name: Gym
options:
  bundleIdPrefix: com.dukhaansin
  deploymentTarget:
    iOS: "17.0"
  developmentLanguage: en
settings:
  base:
    SWIFT_VERSION: "6.0"
    MARKETING_VERSION: "1.0"
    CURRENT_PROJECT_VERSION: "1"
    GENERATE_INFOPLIST_FILE: YES
    DEVELOPMENT_TEAM: ""
    ENABLE_USER_SCRIPT_SANDBOXING: YES
targets:
  Gym:
    type: application
    platform: iOS
    sources:
      - path: Gym
        excludes:
          - Secrets.swift.template
          - "**/.DS_Store"
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.dukhaansin.Gym
        INFOPLIST_KEY_UIApplicationSceneManifest_Generation: YES
        INFOPLIST_KEY_UILaunchScreen_Generation: YES
        INFOPLIST_KEY_UIApplicationSupportsIndirectInputEvents: YES
        INFOPLIST_KEY_UISupportedInterfaceOrientations_iPhone: "UIInterfaceOrientationPortrait"
        INFOPLIST_KEY_CFBundleDisplayName: Gym
        INFOPLIST_KEY_UIRequiredDeviceCapabilities: arm64
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        TARGETED_DEVICE_FAMILY: "1"
        SUPPORTS_MACCATALYST: NO
        SUPPORTS_XR_DESIGNED_FOR_IPHONE_IPAD: NO
